language: node_js
node_js:
  - lts/* 
env:
  - PLATFORM=FIREFOX
addons:
  firefox: "55.0.2"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
services:
  - xvfb
notifications:
  email:
    recipients:
      secure: UuJO0HyaOOQyW1TizhGsiegd0BzodRJdmIXN6SOzJuHb7yai2DejVrpAwFRzxU88EAE5g+t6hb1UWWFtjaw21oUos8wltUMZvCuXLLthJsLldu/932MdwaT06Z3jfACSxHzf/pxfzG73DtejfJiVm2Ch93PKvDu1Y+fv/nM7LAs8jVaHr0R8AEwGrH8IchyqgEqlXpurx7E6ObnWpwSlO+qugUkSMHt5dhazwesLrBx7z0S4rYa1iRwScoRmunoLQMyzYXM+23n/HkDcfotADH8IepBjFn7gB/scASeiStR3CCd64eyejXm9RpTb7LQ+hPZtpgSO2UhH7sKZeg4Tcc1CESDjRWruh6eZ7BNjM3HkbV3xzDdlmOxmYG9nWJvjStBn5TRWCAniUARgDzwoOyMvltEujIMXMmK/cfcTK0ZeX5kSjIA2PV+Z87w5qo+QkAyny4otPTZEvst8ETnngzVGBuF63PETBSw9HI8ZYmDznneKikMdXxtJ6FM+beg1sSAKTxMBdT1N8kWie9lNbKwraHknyqMt+g5bNVtMJBUe7JC55lpkkzgm6/Ot84plCepWi0NlkuM6GihMt4jcOiVXLNdlLQlEBoPF5SZihPMZadp6/VLGHwR7Ej//ZWcE3Srkyd6C1pDc40H82ErKowlNwomcVLg5P0vQm9LYdsQ=
    on_failure: always
